### ISSUE TITLE
Uncaught Error: Class 'PHP_CodeSniffer_CLI'

### ISSUE THREAD

**Issue by GIANTCRAB** [php-fig-rectified/psr2r-sniffer#14]
Hi, 

I've got Code sniffer installed via composer (dev dependency) but I'm getting this issue. I'm running PHP 7.1
```
PHP Fatal error:  Uncaught Error: Class 'PHP_CodeSniffer_CLI' not found in /vendor/fig-r/psr2r-sniffer/PSR2R/Tools/Sniffer.php:68
Stack trace:
#0 /vendor/fig-r/psr2r-sniffer/bin/sniff.php(22): PSR2R\Tools\Sniffer->sniff()
#1 {main}
  thrown in /vendor/fig-r/psr2r-sniffer/PSR2R/Tools/Sniffer.php on line 68
[woohuiren@localhost atom-api]$ vendor/bin/sniff
PHP Fatal error:  Uncaught Error: Class 'PHP_CodeSniffer_CLI' not found in /vendor/fig-r/psr2r-sniffer/PSR2R/Tools/Sniffer.php:68
Stack trace:
#0 /vendor/fig-r/psr2r-sniffer/bin/sniff.php(22): PSR2R\Tools\Sniffer->sniff()
#1 {main}
  thrown in /vendor/fig-r/psr2r-sniffer/PSR2R/Tools/Sniffer.php on line 68\

```

I went to look at the file. Apparently its just `use use PHP_CodeSniffer_CLI;`. Is there a better way to go about? I could possibly contribute something to allow the use of dev dependency version of PHP code sniffer.

Thanks again

EDIT: I took a look and apparenly #11 fixes this?

**Comment by JeanValJeann** [comment]
Save error on windows.

**Comment by markvincent9** [comment]
same error

**Comment by dereuromark** [comment]
Someone needs to rebase then we can merge.
